on: 
  push:
   branches:
    - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: dbvertex.com
        username: ${{ secrets.FTP_PASSWORD }}
        password: ${{ secrets.FTP_USERNAME }}
        server-dir: /production.cipher.co.tz/